services:
  db:
    env_file:
      - .env
    container_name: $DATABASE_CONTAINER_NAME
    image: ankane/pgvector
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
     - 5432:5432

volumes:
  db_data:
